export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';

export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_ERROR = 'GET_GAMES_ERROR';

export const GET_GAME_BY_ID = 'GET_GAME_BY_ID';
export const GET_GAME_BY_ID_SUCCESS = 'GET_GAME_BY_ID_SUCCESS';
export const GET_GAME_BY_ID_ERROR = 'GET_GAME_BY_ID_ERROR';

export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_ERROR = 'CREATE_GAME_ERROR';

export const SEARCH_GAME_BY_NAME = 'SEARCH_GAME_BY_NAME';
export const SEARCH_GAME_BY_NAME_SUCCESS = 'SEARCH_GAME_BY_NAME_SUCCESS';
export const SEARCH_GAME_BY_NAME_ERROR = 'SEARCH_GAME_BY_NAME_ERROR';

export const FILTER_GAMES_BY_GENRE_INIT = 'FILTER_GAMES_BY_GENRE_INIT';
export const FILTER_GAMES_BY_GENRE = 'FILTER_GAMES_BY_GENRE';
export const FILTER_GAMES_BY_GENRE_SUCCESS = 'FILTER_GAMES_BY_GENRE_SUCCESS';
export const FILTER_GAMES_BY_GENRE_ERROR = 'FILTER_GAMES_BY_GENRE_ERROR';

export const FILTER_GAMES_BY_ORIGIN_INIT = 'FILTER_GAMES_BY_ORIGIN_INIT';
export const FILTER_GAMES_BY_ORIGIN = 'FILTER_GAMES_BY_ORIGIN';

export const PAGINATE_GAMES_INIT = 'PAGINATE_GAMES_INIT';
export const PAGINATE_GAMES = 'PAGINATE_GAMES';

export const ORDER_GAMES_BY_NAME_INIT = 'ORDER_GAMES_BY_NAME_INIT';
export const ORDER_GAMES_BY_NAME = 'ORDER_GAMES_BY_NAME';
export const ORDER_GAMES_BY_RATING = 'ORDER_GAMES_BY_RATING';